---
- name: set Cronjob for notifications
  cron:
    name: "Nextcloud Cronjob"
    minute: "*/15"
    user: "{{ nextcloud.user }}"
    job: "php {{ nextcloud.server_path }}/cron.php"
    cron_file: "nextcloud"
  when: (nextcloud_background_cron | bool)

- name: Set Cron method to Crontab
  become_user: "{{ nextcloud.user }}"
  become_flags: "{{ ansible_become_flags | default(omit) }}"
  become: yes
  command: php occ background:cron
  args:
    chdir: "{{ nextcloud.server_path }}"
  when: (nextcloud_background_cron | bool)
