---
- name: PostgreSQL packages are installed
  package:
    name:
      - "postgresql"
      - "php{{ php_ver }}-pgsql"
      - "python3-psycopg2"
    state: "present"

- name: nextcloud role is created.
  postgresql_user:
    name: "{{ nextcloud.db_user }}"
    password: "{{ nextcloud.db_user_pwd }}"
    encrypted: yes
    state: present
    role_attr_flags: CREATEDB
  become_user: postgres
  become: yes

- name: nextcloud database is created.
  postgresql_db:
    name: "{{ nextcloud.db_name }}"
    state: present
    owner: "{{ nextcloud.db_user }}"
  become_user: postgres
  become: yes
