---
- name: remove some commented line in php-fpm conf
  lineinfile:
    dest: "{{ php_dir }}/fpm/pool.d/www.conf"
    regexp: '^\;env'
    state: absent
  notify: reload php-fpm

- name: Add path variable to php-fpm
  blockinfile:
    dest: "{{ php_dir }}/fpm/pool.d/www.conf"
    insertafter: '^; Default Value: clean env$'
    marker: "; {mark} ANSIBLE MANAGED BLOCK"
    block: |
      env[HOSTNAME] = $HOSTNAME
      env[PATH] = $PATH
      env[TMP] = /tmp
      env[TMPDIR] = /tmp
      env[TEMP] = /tmp
  notify: reload php-fpm

- name: enable PHP OPcache for php.ini
  lineinfile:
    dest: "{{ php_dir }}/fpm/php.ini"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: 'opcache.enable=0', line: 'opcache.enable=1' }
    - { regexp: 'opcache.enable_cli', line: 'opcache.enable_cli=1' }
    - { regexp: 'opcache.interned_strings_buffer', line: 'opcache.interned_strings_buffer=8' }
    - { regexp: 'opcache.max_accelerated_files', line: 'opcache.max_accelerated_files=10000' }
    - { regexp: 'opcache.memory_consumption', line: 'opcache.memory_consumption=128' }
    - { regexp: 'opcache.save_comments', line: 'opcache.save_comments=1' }
    - { regexp: 'opcache.revalidate_freq', line: 'opcache.revalidate_freq=1' }
  notify: reload php-fpm

- name: php handler configuration is present
  template:
    dest: /etc/nginx/sites-available/php_handler.cnf
    src: templates/nginx_php_handler.j2
  notify: reload webserver

- name: php handler is enabled
  file:
    path: /etc/nginx/sites-enabled/php_handler
    src: /etc/nginx/sites-available/php_handler.cnf
    state: link
  notify: reload webserver

- name: generate Nextcloud configuration for nginx
  template:
    dest: /etc/nginx/sites-available/nc_{{ nextcloud.instance_name }}.cnf
    src: "templates/{{nextcloud.webserver}}_nc.j2"
  notify: reload webserver

- name: Enable Nextcloud in nginx conf
  file:
    path: /etc/nginx/sites-enabled/nc_{{ nextcloud.instance_name }}
    src: /etc/nginx/sites-available/nc_{{ nextcloud.instance_name }}.cnf
    state: link
  notify: reload webserver

- name: Disable nginx default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: nextcloud_disable_websrv_default_site | bool
  notify: reload webserver

