---
- name: enable APC for php CLI
  lineinfile:
    dest: "{{ php_dir }}/cli/php.ini"
    line: "apc.enable_cli = 1"
    insertbefore: "^; End:$"
    state: present
    # validate: "/usr/sbin/{{ php_bin }} -t #%s"

- name: enable PHP OPcache for php.ini
  lineinfile:
    dest: "{{ php_dir }}/apache2/php.ini"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  loop:
    - { regexp: 'opcache.enable=0', line: 'opcache.enable=1' }
    - { regexp: 'opcache.enable_cli', line: 'opcache.enable_cli=1' }
    - { regexp: 'opcache.interned_strings_buffer', line: 'opcache.interned_strings_buffer=8' }
    - { regexp: 'opcache.max_accelerated_files', line: 'opcache.max_accelerated_files=10000' }
    - { regexp: 'opcache.memory_consumption', line: 'opcache.memory_consumption=128' }
    - { regexp: 'opcache.save_comments', line: 'opcache.save_comments=1' }
    - { regexp: 'opcache.revalidate_freq', line: 'opcache.revalidate_freq=1' }
    # validate: "/usr/sbin/{{ php_bin }} -t #%s"
  notify: reload webserver

- name: Required Apache2 modules are enabled
  apache2_module: 
    state: present
    name: "{{ item }}"
  loop:
    - rewrite
    - headers
    - env
    - dir
    - mime
  notify: restart webserver

- name: generate Nextcloud configuration for apache
  template:
    dest: /etc/apache2/sites-available/nc_{{ nextcloud.instance_name }}.conf
    src: "templates/{{nextcloud.webserver}}_nc.j2"
  notify: reload webserver

- name: Enable Nextcloud site in apache conf
  file:
    path: /etc/apache2/sites-enabled/nc_{{ nextcloud.instance_name }}.conf
    src: /etc/apache2/sites-available/nc_{{ nextcloud.instance_name }}.conf
    state: link
  notify: reload webserver

- name: Disable apache default site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  when: nextcloud_disable_websrv_default_site | bool
  notify: reload webserver

